# Generated by Django 4.1.4 on 2023-01-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_articles_article_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
